version: "3.7"

services:
  backend:
    build: ./backend
    image: edmundlai/content-agg-backend:latest
    env_file:
      - ./backend/.env
    ports:
      - 5000:5000

  client:
    build: ./client
    image: edmundlai/content-agg-client:latest
    ports:
      - 3000:3000
